# [module.hugoVersion]
# min = "0.111.3"

[[module.imports]]
path = "github.com/hugomods/icons/vendors/bootstrap"

[[module.imports]]
path = "github.com/hugomods/icons/vendors/simple-icons"

[[module.imports]]
path = "github.com/hugomods/icons/vendors/font-awesome"

[[module.imports]]
path = "github.com/hbstack/base"

[[module.imports]]
path = "github.com/hbstack/header/modules/language-picker"

[[module.imports]]
path = "github.com/hbstack/header/modules/socials"

[[module.imports]]
path = "github.com/hbstack/header/modules/theme-toggle"

[[module.imports]]
path = "github.com/hbstack/background-image"

[[module.imports]]
path = "github.com/hugomods/seo/modules/favicons"

[params.seo.favicons]
icon = "images/logo.png"

[params.hb.header]

[params.hb.theme_start]

[params.hb.theme_start.search_engines.baidu]
weight = 3
url = "https://www.baidu.com/s"
input_name = "wd"
icon = "baidu"
icon_color = "#2932e1"

[params.hb.theme_start.search_engines.bing]
weight = 2
url = "https://www.bing.com/search"
input_name = "q"
icon = "microsoftbing"
icon_color = "#258ffa"

[params.hb.theme_start.search_engines.duckduckgo]
weight = 4
identifier = "duckduckgo"
url = "https://duckduckgo.com/"
input_name = "q"
icon = "duckduckgo"
icon_color = "#de5833"

[params.hb.theme_start.search_engines.google]
weight = 1
url = "https://www.google.com/search"
input_name = "q"
icon = "google"
icon_color = "#4285f4"

[params.hb.theme_start.search_engines.sogou]
disable = true
url = "https://www.sogou.com/web"
input_name = "query"
icon = "sogou"
icon_color = "#fb6022"

[params.hb.theme_start.search_engines.wikipedia]
disable = true
url = "https://en.wikipedia.org/w/index.php"
input_name = "search"
icon = "wikipedia"
icon_color = "#000000"

[params.hb.theme_start.search_engines.yahoo]
disable = true
weight = 5
url = "https://search.yahoo.com/search"
input_name = "p"
icon = "yahoo"
icon_color = "#6001d2"

[params.hb.theme_start.search_engines.yandex]
disable = true
weight = 6
url = "https://yandex.com/search"
input_name = "text"
icon = "yandex"
icon_vendor = "fab"
icon_color = "#fc3f1d"

# [params.hugopress.modules.hb-theme-start.hooks.body-end]
# cacheable = true
